---

- hosts: all
  become: true
  tasks:

  - name: add php support for apache and install apache
    package:
      name:
        - "{{ php_package }}"
        - "{{ apache_package ]}"
      state: latest
      update_cache: yes
